---
resources:
  - source.yaml
  - pvc.yaml
  - vm.yaml
commonLabels:
  appname: regional-dr
secretGenerator:
  - name: my-public-key
    files:
      - test_rsa.pub
generatorOptions:
  disableNameSuffixHash: true
